source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#use_frameworks!

target 'DeviceUniqueId_Example' do
  pod 'DeviceUniqueId', :path => '../'
#    pod 'DeviceUniqueId', '~> 1.0'
end

#target 'DeviceUniqueId_Tests', :exclusive => true do
#  pod 'DeviceUniqueId', :path => '../'
#
#  
#end
